spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql-prod:3306/delivery_db?serverTimezone=Asia/Kolkata
    username: root
    password: Manoj2@@@
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.zuufa.in/realms/zuufa

keycloak:
  service-auth:
    enabled: true
    token-url: https://keycloak.zuufa.in/realms/zuufa/protocol/openid-connect/token
    client-id: service
    client-secret: KUx5LcbRWMTxTGboi9EnkSlp3sp1nOhw

EUREKA_URL: 'http://eureka:8761/eureka/'
